name: Trigger auto deployment for containerapp app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ansalemo-aca-app-AutoDeployTrigger-ff2eb9d1-a698-4921-b754-bb2c04ace58b.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ansalemoacr.azurecr.io
          username: ${{ secrets.ANSALEMOACAAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMOACAAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ansalemoacr.azurecr.io/ansalemo-aca-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOACAAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n ansalemo-aca-app -g ansalemo-rg --server ansalemoacr.azurecr.io --username  ${{ secrets.ANSALEMOACAAPP_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMOACAAPP_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-aca-app -g ansalemo-rg --image ansalemoacr.azurecr.io/ansalemo-aca-app:${{ github.sha }}