name: Trigger auto deployment for ansalemo-branch-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ansalemo-branch-test-AutoDeployTrigger-a9d8cd11-0c80-4dd9-b790-5d809d8dd0c8.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ansalemoacr.azurecr.io
          username: ${{ secrets.ANSALEMOBRANCHTEST_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMOBRANCHTEST_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ansalemoacr.azurecr.io/ansalemo-branch-test:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOBRANCHTEST_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ansalemo-branch-test -g ansalemo-rg --server ansalemoacr.azurecr.io --username  ${{ secrets.ANSALEMOBRANCHTEST_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMOBRANCHTEST_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-branch-test -g ansalemo-rg --image ansalemoacr.azurecr.io/ansalemo-branch-test:${{ github.sha }}
