name: Trigger auto deployment for ansalemo-ping-test

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ansalemo-ping-test-AutoDeployTrigger-062f74fc-f50b-422a-b7bb-b69ef3b74260.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOPINGTEST_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v1
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: ansalemoacr.azurecr.io
          registryUsername: ${{ secrets.ANSALEMOPINGTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ANSALEMOPINGTEST_REGISTRY_PASSWORD }}
          containerAppName: ansalemo-ping-test
          resourceGroup: ansalemo-rg
          imageToBuild: ansalemoacr.azurecr.io/ansalemo-ping-test:${{ github.sha }}
          

     

