name: Trigger auto deployment for containerapp ansalemo-ca-test-php

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ansalemo-ca-test-php-AutoDeployTrigger-0e25fec0-a8e7-403c-a159-286c2ac61aab.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: https://ajssalemo.docker.io
          username: ${{ secrets.ANSALEMOCATESTPHP_REGISTRY_USERNAME }}
          password: ${{ secrets.ANSALEMOCATESTPHP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://ajssalemo.docker.io/ansalemo-ca-test-php:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ANSALEMOCATESTPHP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n ansalemo-ca-test-php -g ansalemo-ca-test-rg --server https://ajssalemo.docker.io --username  ${{ secrets.ANSALEMOCATESTPHP_REGISTRY_USERNAME }} --password ${{ secrets.ANSALEMOCATESTPHP_REGISTRY_PASSWORD }}
            az containerapp update -n ansalemo-ca-test-php -g ansalemo-ca-test-rg --image https://ajssalemo.docker.io/ansalemo-ca-test-php:${{ github.sha }}
