# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Linux Container PHP Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: ansalemocontainerregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ansalemocontainerregistry.azurecr.io/ansalemo-php-wafc-githubactions:${{ github.sha }}
        docker push ansalemocontainerregistry.azurecr.io/ansalemo-php-wafc-githubactions:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ansalemo-php-wafc-githubactions'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_96A786AF29204F989FAA2469FCD8089C }}
          images: 'ansalemocontainerregistry.azurecr.io/ansalemo-php-wafc-githubactions:${{ github.sha }}'
